version: '2'

services:
  wagtail:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /www/wagtail_data/db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
  
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment:
      - DJANGO_SERVER_ADDR=wagtail:8000
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - wagtail