# Generated by Django 5.0.3 on 2024-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicesoffered'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Banner section title', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='servicesoffered_content',
            field=models.CharField(blank=True, help_text='Services offered content', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='servicesoffered_title',
            field=models.CharField(blank=True, help_text='Services offered title', max_length=255),
        ),
    ]
