# Generated by Django 5.0.3 on 2024-04-04 17:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicespage_engagment_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagmentcard',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='engagmentcard',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='engagmentcard',
            name='data',
            field=models.CharField(blank=True, help_text='data', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='datasection_subtitle',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='datasection_title',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AlterField(
            model_name='engagmentcard',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasection_stat', to='services.servicespage'),
        ),
        migrations.AlterField(
            model_name='engagmentcard',
            name='title',
            field=models.CharField(blank=True, help_text='title', max_length=255),
        ),
    ]
