# Generated by Django 5.0.3 on 2024-04-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_servicespage_testimonial_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicespage',
            old_name='testimonial_desigation',
            new_name='testimonial_designation',
        ),
    ]
