# Generated by Django 5.0.3 on 2024-04-04 18:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_testimonial_desigation_servicespage_testimonial_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='faqsection_title_bottom',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='faqsection_title_top',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.CreateModel(
            name='faqsectionfaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(blank=True, help_text='data', max_length=255)),
                ('answer', models.CharField(blank=True, help_text='title', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqsection_faq', to='services.servicespage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
