# Generated by Django 5.0.3 on 2024-04-09 11:53

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_servicespage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='body',
            field=wagtail.fields.StreamField([('herosecion', wagtail.blocks.StructBlock([('titles', wagtail.blocks.StreamBlock([('title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('subtitle', wagtail.blocks.CharBlock(form_classname='subtitle', required=True))]))])), ('include_quick_testimonials', wagtail.blocks.BooleanBlock(required=False))])), ('herosecion2', wagtail.blocks.StructBlock([('titles', wagtail.blocks.StreamBlock([('title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('subtitle', wagtail.blocks.CharBlock(form_classname='subtitle', required=True))]))])), ('include_quick_testimonials', wagtail.blocks.BooleanBlock(required=False))]))], null=True),
        ),
    ]
