# Generated by Django 5.0.3 on 2024-04-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_businesshelpedcard_point1_businesshelpedcard_point2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='banner_sidetitle',
            field=models.CharField(blank=True, help_text='Banner section title', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='businesshelped_sidetitle',
            field=models.CharField(blank=True, help_text='Business helped title', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='datasection_sidetitle',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='engagment_sidetitle',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='faqsection_sidetitle',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='servicesoffered_sidetitle',
            field=models.CharField(blank=True, help_text='Services offered title', max_length=255),
        ),
    ]
