# Generated by Django 5.0.3 on 2024-04-24 06:35

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_servicespage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='body',
            field=wagtail.fields.StreamField([('herosection', wagtail.blocks.StructBlock([('sidetitles', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('titles', wagtail.blocks.StreamBlock([('title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('subtitle', wagtail.blocks.CharBlock(form_classname='subtitle', required=True))]))])), ('include_companies', wagtail.blocks.BooleanBlock(required=False)), ('include_fullimage', wagtail.blocks.BooleanBlock(required=False)), ('primary_button', wagtail.blocks.StreamBlock([('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('link', wagtail.blocks.PageChooserBlock(can_choose_root=True))]))])), ('company_image', wagtail.blocks.StreamBlock([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True))]))])), ('image_cover', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_decor', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True),
        ),
    ]
