# Generated by Django 5.0.4 on 2024-05-07 10:49

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_servicespage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='faqsection_title_bottom',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='faqsection_title_top',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='faqsection_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AlterField(
            model_name='bannerrow',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=450),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='banner_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Banner section title', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='businesshelped_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='datasection_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='engagment_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='servicesoffered_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services offered content', max_length=255),
        ),
    ]
