# Generated by Django 5.0.4 on 2024-05-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_alter_bannerrow_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='faqsection_toptitle',
            field=models.CharField(blank=True, help_text='Business helped subtitle', max_length=255),
        ),
    ]
