# Generated by Django 5.0.7 on 2024-08-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_servicesoffered_card_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqsectionfaq',
            name='answer',
            field=models.CharField(blank=True, help_text='title', max_length=3000),
        ),
    ]
