# Generated by Django 5.0.3 on 2024-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_service_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ourworks_nav',
            field=models.CharField(blank=True, help_text='OurWorks Navigation Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='service_nav',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
