# Generated by Django 5.0.3 on 2024-04-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_enquirebot_cofounder_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='enquirebot_CoFounder_image',
            new_name='enquirebot_cofounder_image',
        ),
    ]
