# Generated by Django 5.0.3 on 2024-04-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_blogs_clutchreview_homepage_blogs_crmemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_service_title',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
