# Generated by Django 5.0.3 on 2024-04-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_home_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_service_subtitle',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
