# Generated by Django 5.0.3 on 2024-04-02 09:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_home_service_content_homeservicecard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeservicecard',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='homeservicecard',
            name='home_page',
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='page',
            field=modelcluster.fields.ParentalKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='service_cards', to='home.homepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeservicecard',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
