# Generated by Django 5.0.3 on 2024-04-02 17:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_home_process_content_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProcessCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('point1', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('point2', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('point3', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('point4', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('line_svg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_cards', to='home.homepage')),
                ('pointer_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
