# Generated by Django 5.0.3 on 2024-04-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homeprocesscard_dotted_mesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_process_technology_content',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_process_technology_title',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
