# Generated by Django 5.0.3 on 2024-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_homepage_home_rating_testimonial_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_industries_content',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_industries_subtitle',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_industries_title',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
