# Generated by Django 5.0.3 on 2024-04-03 10:43

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_aboutuspage'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='industriessectioncard',
            name='card_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='card_title',
            field=models.CharField(blank=True, help_text='card title', max_length=255),
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='page',
            field=modelcluster.fields.ParentalKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='industries_cards', to='home.homepage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IndusrtrialSectionCardPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('point', models.CharField(blank=True, help_text='card title', max_length=255)),
                ('indusrtrial_section_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries_cards_point', to='home.industriessectioncard')),
                ('pointer_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AboutusPage',
        ),
    ]
