# Generated by Django 5.0.3 on 2024-04-03 10:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_industriessectioncard_card_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industriessectioncard',
            options={},
        ),
        migrations.RemoveField(
            model_name='industriessectioncard',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='indusrtrialsectioncardpoint',
            name='indusrtrial_section_card',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries_cards_point', to='home.industriessectioncard'),
        ),
    ]
