# Generated by Django 5.0.3 on 2024-04-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_delete_navitem_delete_servicespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='ourworks_nav',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_nav',
        ),
    ]
