# Generated by Django 5.0.3 on 2024-04-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
        ('home', '0029_remove_homepage_ourworks_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='navbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='components.navbar'),
        ),
    ]
