# Generated by Django 5.0.3 on 2024-04-05 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_button_button'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_service_button_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_service_button_text',
            field=models.CharField(blank=True, help_text='card title', max_length=255),
        ),
        migrations.DeleteModel(
            name='Button',
        ),
    ]
