# Generated by Django 5.0.3 on 2024-04-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_homepage_home_service_button_icon_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_process_content',
        ),
        migrations.RemoveField(
            model_name='homeprocesscard',
            name='dotted_mesh',
        ),
        migrations.AddField(
            model_name='homepage',
            name='dotted_mesh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
