# Generated by Django 5.0.3 on 2024-04-08 02:21

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_homeherosection'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCaseStudiesCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('data1', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('data2', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('label1', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('label2', models.CharField(blank=True, help_text='Services Navigation Link', max_length=255)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='casestudies_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
