# Generated by Django 5.0.3 on 2024-04-09 07:12

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_homepage_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='herosection',
            field=wagtail.fields.StreamField([('herosecion', wagtail.blocks.StructBlock([]))], null=True),
        ),
    ]
