# Generated by Django 5.0.3 on 2024-04-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_homepage_herosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeHeroSection',
        ),
    ]
