# Generated by Django 5.0.3 on 2024-04-17 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_alter_aboutuspage_body_alter_blogpage_body_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indusrtrialsectioncardpoint',
            name='pointer_icon',
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='pointer_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
