# Generated by Django 5.0.3 on 2024-04-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_remove_indusrtrialsectioncardpoint_pointer_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industriessectioncard',
            name='point1',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='point2',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='point3',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='point4',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='industriessectioncard',
            name='point5',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
