# Generated by Django 5.0.3 on 2024-04-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_industriessectioncard_point1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeprocesscard',
            old_name='line_svg',
            new_name='final_pointer_icon',
        ),
    ]
