# Generated by Django 5.0.3 on 2024-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_contactuspage_alter_aboutuspage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_process_sidetitle',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_service_sidetitle',
            field=models.CharField(blank=True, help_text='Services Side Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_service_title',
            field=models.CharField(blank=True, help_text='Services Title', max_length=255),
        ),
    ]
