# Generated by Django 5.0.3 on 2024-04-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_homepage_home_industries_sidetitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='home_testimonials_subtitle',
            new_name='home_casestudies_sidetitle',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='home_testimonials_title',
            new_name='home_whyreckonsys_sidetitle',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_service_content',
            field=models.CharField(blank=True, help_text='Services Content', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_service_subtitle',
            field=models.CharField(blank=True, help_text='Services Subtitle', max_length=255),
        ),
    ]
