# Generated by Django 5.0.3 on 2024-04-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0099_alter_homepage_outline_grey_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='outline_grey_button',
        ),
    ]
