# Generated by Django 5.0.3 on 2024-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_alter_aboutuspage_body_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecasestudiescard',
            name='bgcolor',
            field=models.CharField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
