# Generated by Django 5.0.3 on 2024-04-25 09:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_alter_aboutuspage_body_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homewhyreckonsycard',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
