# Generated by Django 5.0.3 on 2024-04-25 17:53

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_alter_aboutuspage_body_alter_blogpage_body_and_more'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('PrivacyPolicy', wagtail.blocks.StructBlock([('sidetitle', wagtail.blocks.CharBlock(form_classname='sidetitle', required=True)), ('title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('datetitle', wagtail.blocks.CharBlock(form_classname='lastupdatedtitle', required=True)), ('date', wagtail.blocks.CharBlock(form_classname='date', required=True)), ('welcomeline', wagtail.blocks.CharBlock(form_classname='date', required=True)), ('commitment', wagtail.blocks.CharBlock(form_classname='date', required=True)), ('mainimage', wagtail.images.blocks.ImageChooserBlock(required=False))]))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
