# Generated by Django 5.0.3 on 2024-04-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_privacypage'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivacyPage',
            new_name='PrivacyPolicyPage',
        ),
    ]
