# Generated by Django 5.0.3 on 2024-04-25 18:12

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_rename_privacypage_privacypolicypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicypage',
            name='body',
            field=wagtail.fields.StreamField([('PrivacyPolicy', wagtail.blocks.StructBlock([('sidetitle', wagtail.blocks.CharBlock(form_classname='sidetitle', required=True)), ('title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('datetitle', wagtail.blocks.CharBlock(form_classname='lastupdatedtitle', required=True)), ('date', wagtail.blocks.CharBlock(form_classname='date', required=True)), ('welcomeline', wagtail.blocks.CharBlock(form_classname='date', required=True)), ('commitment', wagtail.blocks.CharBlock(form_classname='date', required=True)), ('mainimage', wagtail.images.blocks.ImageChooserBlock(required=False)), ('decorimage', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('ContactusTesimonial', wagtail.blocks.StructBlock([('clutch_logo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('testimonialcards', wagtail.blocks.StreamBlock([('testimonialcard', wagtail.blocks.StructBlock([('review', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('name', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('designation', wagtail.blocks.CharBlock(form_classname='title', required=True))]))]))]))], null=True),
        ),
    ]
