# Generated by Django 5.0.4 on 2024-05-03 17:01

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0135_personalblogpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalblogpage',
            name='blogAuthor',
        ),
        migrations.AlterField(
            model_name='personalblogpage',
            name='blogbody',
            field=wagtail.fields.StreamField([('blogbody', wagtail.blocks.StructBlock([('profile_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('designation', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('abouttheauthor', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('page_title', wagtail.blocks.RichTextBlock(form_classname='title', required=True))]))], null=True),
        ),
    ]
