# Generated by Django 5.0.4 on 2024-05-07 10:49

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0151_alter_aboutuspage_body_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_casestudies_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_industries_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_process_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_rating_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_service_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Subtitle', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_whyreckonsys_subtitle',
            field=wagtail.fields.RichTextField(blank=True, help_text='Services Navigation Link', max_length=255),
        ),
    ]
