# Generated by Django 5.0.4 on 2024-05-08 05:16

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0153_alter_aboutuspage_body_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalblogpage',
            name='blogheader',
            field=wagtail.fields.StreamField([('blogheader', wagtail.blocks.StructBlock([('blogs_url', wagtail.blocks.PageChooserBlock(required=False)), ('page_title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('headline', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('category_title', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('publish_date', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('cover_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('tags', wagtail.blocks.StreamBlock([('tags', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(form_classname='title', required=True))]))]))]))], null=True),
        ),
    ]
