# Generated by Django 5.0.4 on 2024-05-21 14:47

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0166_alter_personalblogpage_blogbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledpersonalblogpage',
            name='blogbody',
            field=wagtail.fields.StreamField([('blogbody', wagtail.blocks.StructBlock([('profile_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('designation', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('about_the_author', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('twitter_url', wagtail.blocks.URLBlock(form_classname='link', required=False)), ('linkedin_url', wagtail.blocks.URLBlock(form_classname='link', required=False)), ('facebook_url', wagtail.blocks.URLBlock(form_classname='link', required=False)), ('url', wagtail.blocks.URLBlock(form_classname='link', required=True)), ('blog_text', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.RichTextBlock()), ('tableblock', wagtail.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(required=False, table_options={'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut', '---------', 'alignment']}))]))]))]))], null=True),
        ),
    ]
