# Generated by Django 5.0.4 on 2024-05-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0168_alter_personalblogpage_blogbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabledpersonalblogPage',
        ),
    ]
