# Generated by Django 5.0.4 on 2024-05-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0169_delete_tabledpersonalblogpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blogs_clutchreview',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogs_crmemail',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogs_solvingcrmemail',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='casestudies_saascard_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='casestudies_seniorcentriccard_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='enquirebot_cofounder_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='great_place_to_work_badge',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_sidetitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_testimonial_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_testimonial_designation',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_testimonial_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_testimonial_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_rating_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
    ]
