# Generated by Django 5.0.4 on 2024-06-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0172_alter_customserviespage_body'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomServiesPage',
            new_name='CustomServicesPage',
        ),
    ]
