# Generated by Django 5.0.6 on 2024-06-27 05:03

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0196_alter_personalblogpage_blogbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalblogpage',
            name='blogbody',
            field=wagtail.fields.StreamField([('blogbody', wagtail.blocks.StructBlock([('profile_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('designation', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('about_the_author', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('twitter_url', wagtail.blocks.URLBlock(form_classname='link', required=False)), ('linkedin_url', wagtail.blocks.URLBlock(form_classname='link', required=False)), ('facebook_url', wagtail.blocks.URLBlock(form_classname='link', required=False)), ('url', wagtail.blocks.URLBlock(form_classname='link', required=True)), ('blog_content', wagtail.blocks.StreamBlock([('richtext', wagtail.blocks.StructBlock([('blog_text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'p', 'bold', 'hr', 'italic', 'code', 'ol', 'ul', 'link', 'image', 'blockquote'], form_classname='title', required=True))])), ('tableblock', wagtail.blocks.StructBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(required=False, table_options={'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'undo', 'redo', '---------', 'copy', 'cut', '---------', 'alignment']}))])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('width', wagtail.blocks.CharBlock(form_classname='title', required=False))]))]))]))], null=True),
        ),
    ]
