# Generated by Django 5.0.7 on 2024-08-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0241_alter_customservicespage_body_alter_uiuxpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='customservicespage',
            name='faq_script',
            field=models.CharField(blank=True, help_text='FAQ Script', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='home_service_sidetitle',
            field=models.CharField(blank=True, help_text='Services side Title', max_length=255),
        ),
    ]
