# Generated by Django 5.0.7 on 2024-08-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0242_customservicespage_faq_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservicespage',
            name='faq_script',
            field=models.CharField(blank=True, help_text='FAQ Script', max_length=5000),
        ),
    ]
