# Generated by Django 5.0.7 on 2024-08-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0252_industrypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypage',
            name='faq_script',
        ),
    ]
