# Generated by Django 5.0.3 on 2024-04-09 05:49

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_remove_navbar_ourworks_nav_remove_navbar_service_nav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='navbar',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='navitems', to='components.navbar'),
        ),
    ]
