# Generated by Django 5.0.3 on 2024-04-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_alter_navitem_navbar'),
        ('home', '0045_delete_homeherosection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Herosection',
        ),
    ]
