# Generated by Django 5.0.3 on 2024-04-23 07:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_alter_footeritems_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SevicesOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('service', models.CharField(blank=True, help_text='Services Offred', max_length=255)),
                ('contact', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicesoptions', to='components.contact')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
