# Generated by Django 5.0.4 on 2024-05-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0021_footer_images_footerimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='images',
        ),
    ]
