# Generated by Django 5.0.4 on 2024-05-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_remove_footer_images'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcomebackmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='Navigation link', max_length=255)),
                ('content', models.CharField(blank=True, help_text='Navigation link', max_length=255)),
                ('btn_text', models.CharField(blank=True, help_text='Navigation link', max_length=255)),
                ('sideimage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
