# Generated by Django 5.0.6 on 2024-07-09 06:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_welcomebackmodel_contactus_page_link'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesMegamenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, help_text='Navigation Link', max_length=255)),
                ('link', models.ForeignKey(help_text='page link', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
                ('megamenu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicesmegaitems', to='components.servicesmegamenu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
