# Generated by Django 5.0.6 on 2024-07-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_servicesmegamenu_servicesmenuitem'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesMenuItem',
            new_name='ServicesMenuItems',
        ),
    ]
