# Generated by Django 5.0.6 on 2024-07-09 09:24

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0026_rename_servicesmenuitem_servicesmenuitems'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmegamenu',
            name='service_page_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='servicesmegamenu',
            name='service_page_text',
            field=models.CharField(blank=True, help_text='contactus Link', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicesmenuitems',
            name='megamenu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicesmenuitems', to='components.servicesmegamenu'),
        ),
    ]
