# Generated by Django 5.0.6 on 2024-07-15 16:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_servicesitems'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('rating', models.CharField(blank=True, help_text='contactus Link', max_length=255)),
                ('text', models.CharField(blank=True, help_text='contactus Link', max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('reviewcards', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewcards', to='components.contact')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
