# Generated by Django 5.0.6 on 2024-07-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0031_reviewcards_cardlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcards',
            name='cardlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
