# Generated by Django 5.0.7 on 2024-08-19 07:05

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0035_alter_technologymenuitems_megamenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologymenuitems',
            name='megamenu',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologymenuitems', to='components.technologymegamenu'),
        ),
    ]
